// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatMessage = { message: string, from: string, to: string, chat_id: string, date: bigint, };
