// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DecodedData = { amount: string, denom: string, receiver: string, sender: string, };
