// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Paket } from "./Paket";

export type IbcRecieve = { "@type": string, packet: Paket, };
