// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coin } from "./Coin";

export type IbcTransfer = { "@type": string, receiver: string, sender: string, sourceChannel: string, sourcePort: string, token: Coin, };
