// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coin } from "./Coin";

export type MessageSend = { "@type": string, fromAddress: string, toAddress: string, amount: Array<Coin>, };
