// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecodedData } from "./DecodedData";
import type { EncodedData } from "./EncodedData";

export type Paket = { destinationChannel: string, destinationPort: string, sourceChannel: string, sourcePort: string, sequence: bigint, } & (DecodedData | EncodedData);
