<script lang="ts">
    import MultiSelect from "../../lib/MultiSelect.svelte";
    import { getTranslator } from "../../stores/translate.svelte";
    let t = getTranslator();
    let {
        value = $bindable()
    }:{
        value:typeof CATEGORIES[number]
    } = $props();

    const CATEGORIES = [
        "category_all",
        "accessories",
        "action_figures",
        "art_supplies",
        "arts_crafts",
        "automotive",
        "automotive_accessories",
        "baby_products",
        "baby_clothing",
        "baby_toys",
        "bakery_items",
        "bakeware",
        "bath_shower_products",
        "beauty",
        "bedding",
        "belts",
        "beverages",
        "bicycle_accessories",
        "board_games",
        "books",
        "fashion_boys",
        "cameras_photography",
        "camping_gear",
        "car_care_products",
        "card_games",
        "cleaning_supplies",
        "clothing",
        "computer_accessories",
        "computers",
        "cookware",
        "craft_supplies",
        "curtains_blinds",
        "cutlery",
        "dairy_products",
        "deals",
        "desk_accessories",
        "digital_music",
        "dolls_accessories",
        "drawing_supplies",
        "electronics",
        "filing_supplies",
        "fitness_apparel",
        "fitness_equipment",
        "footwear",
        "fragrances",
        "frozen_food",
        "furniture",
        "garden_tools",
        "gift_items",
        "fashion_girls",
        "glassware",
        "grocery",
        "haircare",
        "handbags",
        "hats_caps",
        "headphones",
        "hpc",
        "health_supplements",
        "kitchen",
        "home_appliances",
        "home_decor",
        "industrial",
        "jewelry",
        "knitting_crochet_supplies",
        "lighting",
        "lingerie",
        "luggage",
        "mattresses",
        "meat_poultry",
        "fashion_mens",
        "microphones",
        "mobile_accessories",
        "motorcycle_gear",
        "movies_tv",
        "music_instruments",
        "music",
        "musical_accessories",
        "office_furniture",
        "office_supplies",
        "packaging_supplies",
        "painting_supplies",
        "paper_products",
        "party_supplies",
        "personal_care_products",
        "pets",
        "printers_scanners",
        "puzzle_games",
        "rugs_carpets",
        "school_supplies",
        "seafood",
        "security_systems",
        "sewing_supplies",
        "skincare",
        "sleepwear",
        "smart_home_devices",
        "snacks",
        "socks",
        "software",
        "speakers",
        "sporting",
        "sports_equipment",
        "stationery",
        "strollers_car_seats",
        "sunglasses",
        "swimwear",
        "tableware",
        "tools",
        "toys_and_games",
        "travel_accessories",
        "tv_home_theater_systems",
        "underwear",
        "video_game_consoles",
        "videogames",
        "wallets",
        "watches",
        "wedding_supplies",
        "fashion_womens",
        "writing_instruments",
        "smartphone_accessories",
        "collectibles",
        "luxury_goods"
    ];

</script>

<MultiSelect options={CATEGORIES} bind:value multiple={false} label={t.t("gray_strong_monkey_bask")}>
    {#snippet valueRenderer(o)}
        {t.t(o as any)}
    {/snippet}
    {#snippet optionRenderer(o)}
        {t.t(o as any)}
    {/snippet}
</MultiSelect>