export const TUTORIAL_PRODUCT = [{
    title: {
        "en": "iPhone 16, Teal, 128GB, Unlocked (US Version)",
        "es": "iPhone 16, Verde Azulado, 128GB, Desbloqueado (Versión de EE.UU.)",
        "de": "iPhone 16, Türkis, 128GB, Entsperrt (US-Version)",
        "fa": "آیفون ۱۶، رنگ آبی فیروزه‌ای، ۱۲۸ گیگابایت، آنلاک (نسخه آمریکا)",
        "fr": "iPhone 16, Bleu Sarcelle, 128 Go, Débloqué (Version US)",
        "gu": "આઈફોન 16, ટીલ રંગ, 128GB, અનલૉક (યુએસ વર્ઝન)",
        "hi": "iPhone 16, टील रंग, 128GB, अनलॉक (अमेरिकी संस्करण)",
        "ja": "iPhone 16, ティール, 128GB, SIMフリー (米国版)",
        "ko": "iPhone 16, 청록색, 128GB, 언락 (미국 버전)",
        "pl": "iPhone 16, Turkusowy, 128GB, Otwarty (Wersja USA)",
        "pt-br": "iPhone 16, Verde Água, 128GB, Desbloqueado (Versão EUA)",
        "ro": "iPhone 16, Verde Teal, 128GB, Deblocat (Versiunea SUA)",
        "ru": "iPhone 16, Бирюзовый, 128GB, Разлоченный (Американская версия)",
        "tr": "iPhone 16, Cam Göbeği, 128GB, Kilitsiz (ABD Versiyonu)",
        "zh-cn": "iPhone 16, 蓝绿色, 128GB, 无锁版（美国版本）",
        "zh-hk": "iPhone 16, 青綠色, 128GB, 無鎖版（美國版本）",
        "zh-tw": "iPhone 16, 青綠色, 128GB, 無鎖版（美國版本）"
    },
    description: {
        "en": "The iPhone 16 features a sleek design, cutting-edge A18 Bionic chip, advanced camera system, and up to 48 hours of battery life. Experience the future of smartphones.",
        "es": "El iPhone 16 presenta un diseño elegante, el innovador chip A18 Bionic, un sistema de cámaras avanzado y hasta 48 horas de duración de batería. Experimenta el futuro de los teléfonos inteligentes.",
        "de": "Das iPhone 16 bietet ein elegantes Design, den fortschrittlichen A18 Bionic-Chip, ein hochmodernes Kamerasystem und bis zu 48 Stunden Akkulaufzeit. Erleben Sie die Zukunft der Smartphones.",
        "fa": "آیفون ۱۶ دارای طراحی زیبا، تراشه پیشرفته A18 Bionic، سیستم دوربین پیشرفته و عمر باتری تا ۴۸ ساعت است. آینده گوشی‌های هوشمند را تجربه کنید.",
        "fr": "L'iPhone 16 propose un design élégant, une puce A18 Bionic de pointe, un système de caméra avancé et jusqu'à 48 heures d'autonomie. Découvrez le futur des smartphones.",
        "gu": "આઈફોન 16 માં આકર્ષક ડિઝાઇન, અદ્યતન A18 બાયોનિક ચિપ, પ્રगत કેમેરા સિસ્ટમ અને 48 કલાક સુધીની બેટરી લાઈફ છે. સ્માર્ટફોનનો ભવિષ્યનો અનુભવ કરો.",
        "hi": "iPhone 16 में स्टाइलिश डिज़ाइन, अत्याधुनिक A18 बायोनिक चिप, उन्नत कैमरा सिस्टम और 48 घंटे तक की बैटरी लाइफ है। स्मार्टफोन का भविष्य अनुभव करें।",
        "ja": "iPhone 16は、洗練されたデザイン、最先端のA18 Bionicチップ、高度なカメラシステム、最大48時間のバッテリー寿命を備えています。スマートフォンの未来を体験してください。",
        "ko": "iPhone 16은 세련된 디자인, 첨단 A18 Bionic 칩, 고급 카메라 시스템, 최대 48시간의 배터리 수명을 제공합니다. 스마트폰의 미래를 경험하세요.",
        "pl": "iPhone 16 oferuje elegancki design, zaawansowany chip A18 Bionic, nowoczesny system kamer i do 48 godzin pracy na baterii. Doświadcz przyszłości smartfonów.",
        "pt-br": "O iPhone 16 apresenta um design elegante, o avançado chip A18 Bionic, um sistema de câmera inovador e até 48 horas de duração da bateria. Experimente o futuro dos smartphones.",
        "ro": "iPhone 16 dispune de un design elegant, cipul avansat A18 Bionic, un sistem de camere performant și până la 48 de ore de autonomie a bateriei. Descoperă viitorul smartphone-urilor.",
        "ru": "iPhone 16 оснащен элегантным дизайном, передовым чипом A18 Bionic, усовершенствованной системой камер и аккумулятором, работающим до 48 часов. Ощутите будущее смартфонов.",
        "tr": "iPhone 16, şık tasarımı, son teknoloji A18 Bionic çipi, gelişmiş kamera sistemi ve 48 saate kadar pil ömrü ile dikkat çekiyor. Akıllı telefonların geleceğini deneyimleyin.",
        "zh-cn": "iPhone 16 配备时尚设计、先进的 A18 仿生芯片、先进的摄像系统和长达 48 小时的电池续航时间。体验智能手机的未来。",
        "zh-hk": "iPhone 16 配備時尚設計、先進的 A18 仿生晶片、先進的攝影系統和長達 48 小時的電池續航時間。體驗智能手機的未來。",
        "zh-tw": "iPhone 16 配備時尚設計、先進的 A18 仿生晶片、先進的攝影系統和長達 48 小時的電池續航時間。體驗智慧型手機的未來。"
    },
    collection_name: "iPhone 16",
    gallery: [
        `https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-16-finish-select-202409-6-1inch-teal?wid=5120&hei=2880&fmt=webp&qlt=70&.v=UXp1U3VDY3IyR1hNdHZwdFdOLzg1V0tFK1lhSCtYSGRqMUdhR284NTN4L29KblRMQzVUOE4vMXpkMWtFcm9GcXF2TWlpSzUzejRCZGt2SjJUNGl1VEtsS0dZaHBma3VTb3UwU2F6dkc4TGRaWWVaY3B6VTFTdVNEWDF2OTRBYlY&traceId=1`,
        `https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-16-finish-select-202409-6-1inch-teal_AV1?wid=5120&hei=2880&fmt=webp&qlt=70&.v=UXp1U3VDY3IyR1hNdHZwdFdOLzg1V0tFK1lhSCtYSGRqMUdhR284NTN4K05tOGV2bzRuYjBHQm9BRXF6V0NIa1pGQnBBWVp4a3ZSd0Y4NzlDUVE4dUJUU08xVXZOQlVmeWYva2RCcG9vcVVjb0pRV1BLWkpwS3lTdmpyVm9XVnRXVi9BOUVIMG00R2gwMHk0cXVORTFB&traceId=1`,
        `https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-16-finish-select-202409-6-1inch-teal_AV3?wid=5120&hei=2880&fmt=webp&qlt=70&.v=UXp1U3VDY3IyR1hNdHZwdFdOLzg1V0tFK1lhSCtYSGRqMUdhR284NTN4OFBjdm1iTDVHUUIydzA3NnRqc3JwS1pGQnBBWVp4a3ZSd0Y4NzlDUVE4dUJUU08xVXZOQlVmeWYva2RCcG9vcVdsQUl3bUplV0NnaUJoa0N0NXhoVm9NUjhodU9MTHNlVnVUMUtlUmw4RU9R&traceId=1`,
    ],
    attribute_1: {
        "en": "Color",
        "es": "Color",
        "de": "Farbe",
        "fa": "رنگ",
        "fr": "Couleur",
        "gu": "રંગ",
        "hi": "रंग",
        "ja": "カラー",
        "ko": "색상",
        "pl": "Kolor",
        "pt-br": "Cor",
        "ro": "Culoare",
        "ru": "Цвет",
        "tr": "Renk",
        "zh-cn": "颜色",
        "zh-hk": "顏色",
        "zh-tw": "顏色"
    },
    attribute_1_value: {
        "en": "Teal",
        "es": "Verde Azulado",
        "de": "Türkis",
        "fa": "آبی فیروزه‌ای",
        "fr": "Bleu Sarcelle",
        "gu": "ટીલ",
        "hi": "टील",
        "ja": "ティール",
        "ko": "청록색",
        "pl": "Turkusowy",
        "pt-br": "Verde Água",
        "ro": "Verde Teal",
        "ru": "Бирюзовый",
        "tr": "Cam Göbeği",
        "zh-cn": "蓝绿色",
        "zh-hk": "青綠色",
        "zh-tw": "青綠色"
    },
    attribute_2: {
        "en": "Storage",
        "es": "Almacenamiento",
        "de": "Speicher",
        "fa": "فضای ذخیره‌سازی",
        "fr": "Stockage",
        "gu": "સ્ટોરેજ",
        "hi": "स्टोरेज",
        "ja": "ストレージ",
        "ko": "저장 용량",
        "pl": "Pamięć",
        "pt-br": "Armazenamento",
        "ro": "Stocare",
        "ru": "Хранилище",
        "tr": "Depolama",
        "zh-cn": "存储",
        "zh-hk": "存儲",
        "zh-tw": "存儲"
    },
    attribute_2_value: {
        "en": "512GB",
        "es": "512GB",
        "de": "512GB",
        "fa": "512GB",
        "fr": "512 Go",
        "gu": "512GB",
        "hi": "512GB",
        "ja": "512GB",
        "ko": "512GB",
        "pl": "512GB",
        "pt-br": "512GB",
        "ro": "512GB",
        "ru": "512ГБ",
        "tr": "512GB",
        "zh-cn": "512GB",
        "zh-hk": "512GB",
        "zh-tw": "512GB"
    }

}];