export const TUTORIAL_PRODUCT = {
    "title": {
        "en": "Keychron Q6 QMK Custom Mechanical Keyboard",
        "es": "Teclado mecánico personalizado QMK Keychron Q6",
        "de": "Keychron Q6 QMK benutzerdefinierte mechanische Tastatur",
        "fa": "کیبورد مکانیک سفارشی qmk قیرون q6",
        "fr": "Clavier mécanique personnalisé QMK Keychron Q6",
        "gu": "કીક્રોન Q6 QMK કસ્ટમ મેકેનિકલ કીબોર્ડ",
        "hi": "कीचरॉन Q6 QMK कस्टम मैकेनिकल कीबोर्ड",
        "ja": "Keychron Q6 QMK カスタム メカニカル キーボード",
        "ko": "Keychron Q6 QMK 커스텀 기계식 키보드",
        "pl": "Keychron Q6 QMK Niestandardowa klawiatura mechaniczna",
        "pt-br": "Teclado Mecânico Personalizado QMK Keychron Q6",
        "ro": "Tastatură mecanică personalizată QMK Keychron Q6",
        "ru": "Keychron Q6 QMK настраиваемая механическая клавиатура",
        "tr": "Keychron Q6 QMK Özel Mekanik Klavye",
        "zh-cn": "Keychron Q6 QMK 自定义机械键盘",
        "zh-hk": "Keychron Q6 QMK 自定義機械鍵盤",
        "zh-tw": "Keychron Q6 QMK 自定義機械鍵盤"
    },
    "description": {
        "en": "Keychron Q6 is a premium full-size and all-metal mechanical keyboard. With its all-metal CNC machined body, a full-size layout, double-gasket design, QMK/VIA support, and knob option, the Q6 meets all your practical needs and gives you a high-end typing experience.",
        "es": "Keychron Q6 es un teclado mecánico de tamaño completo y metálico de gama alta. Con su cuerpo CNC mecanizado de metal, un diseño de tamaño completo, un diseño de goma doble, soporte QMK/VIA y opción de perilla, el Q6 satisface todas tus necesidades prácticas y te brinda una experiencia de escritura de alta gama.",
        "de": "Keychron Q6 ist eine hochwertige Vollgrößen- und Vollmetall-Mechaniktastatur. Mit ihrem vollmetallischen CNC-gefrästen Gehäuse, einer Vollgrößen-Beschaffenheit, Doppel-Dichtungs-Design, QMK / VIA-Unterstützung und Knopf-Option erfüllt die Q6 alle Ihre praktischen Bedürfnisse und bietet Ihnen eine hochwertige Tipp-Erfahrung.",
        "fa": "Keychron Q6 یک کیبورد مکانیکی تمام سایز و تمام فلز با کیفیت بالا است. با بدنه completamente ماشین کاری شده CNC فلزی، طراحی تمام سایز، طراحی دو گasket، پشتیبانی QMK/VIA و گزینه چرخ، Q6 نیازهای عملی شما را برآورده می کند و یک تجربه تایپینگ با کیفیت بالا را به شما می دهد.",
        "fr": "Le Keychron Q6 est un clavier mécanique haut de gamme et complet en métal. Avec son corps entièrement usiné au CNC en métal, une disposition de pleine taille, un design à joints doubles, une prise en charge QMK/VIA et une option de molette, le Q6 répond à tous vos besoins pratiques et vous offre une expérience de frappe haut de gamme.",
        "gu": "Keychron Q6 એ પ્રેમિયમ ફુલ-સાઈઝ અને સંપૂર્ણ ધાતુનો મશીનિકલ કીબોર્ડ છે. તેના સંપૂર્ણ ધાતુના CNC મશીન્ડ શરીર, ફુલ-સાઈઝ લેઆઉટ, ડબલ-ગેસ્કેટ ડિઝાઈન, QMK / VIA સપોર્ટ, અને નોબ વિકલ્પ સાથે, Q6 તમારી તમામ વ્યાવહારિક જરૂરિયાતોને પૂરી કરે છે અને તમને ઉચ્ચ-સંવેદના ટાઇપિંગ અનુભવ આપે છે.",
        "hi": "Keychron Q6 एक प्रीमियम फुल-साइज और ऑल-मेटल मैकेनिकल कीबोर्ड है। इसके ऑल-मेटल सीएनसी मशीन्ड बॉडी, फुल-साइज लेआउट, डबल-गैसकेट डिज़ाइन, QMK/वीआईए सपोर्ट और नॉब विकल्प के साथ, Q6 आपकी सभी व्यावहारिक आवश्यकताओं को पूरा करता है और आपको एक हाई-एंड टाइपिंग अनुभव प्रदान करता है।",
        "ja": "Keychron Q6はプレミアムのフルサイズで全金属のメカニカルキーボードです。全金属のCNC切削ボディ、フルサイズのレイアウト、ダブルガスケット設計、QMK/VIAのサポート、ノブオプションで、Q6はあなたの実用的なニーズすべてを満たし、高級なタイピング体験を提供します。",
        "ko": "Keychron Q6은 프리미엄 풀사이즈 및 올 메탈 메커니컬 키보드입니다. 올 메탈 CNC 가공 본체, 풀사이즈 레이아웃, 더블 개스켓 디자인, QMK/VIA 지원 및 노브 옵션으로 Q6는 모든 실용적인 필요를 충족시키고 고급 타입 라잉 경험을 제공합니다.",
        "pl": "Keychron Q6 to luksusowa pełnowymiarowa i całkowicie metalowa klawiatura mechaniczna. Z jej całkowicie metalowym korpusem wykonanym metodą CNC, pełnowymiarowym układem, podwójnym projektem uszczelki, obsługą QMK/VIA oraz opcją pokrętła, Q6 spełnia wszystkie Twoje praktyczne potrzeby i zapewnia wysokiej jakości doświadczenie podczas pisania.",
        "pt-br": "O Keychron Q6 é um teclado mecânico premium de tamanho completo e todo em metal. Com seu corpo todo em metal CNC fabricado, um layout de tamanho completo, design de gaxeta dupla, suporte QMK/VIA e opção de controle, o Q6 atende a todas as suas necessidades práticas e oferece uma experiência de digitação de alta qualidade.",
        "ro": "",
        "ru": "Keychron Q6 - это премиальная полноценная и полностью металлическая механическая клавиатура. Благодаря своему цельнометаллическому корпусу, изготовленному методом CNC, полноценной раскладке, конструкции с двойной прокладкой, поддержке QMK/VIA и варианту с поворотной ручкой, Q6 удовлетворяет все ваши практические потребности и обеспечивает высококлассный опыт набора текста.",
        "tr": "Keychron Q6, metal CNC işlemleriyle üretilen gövdesi, tam boyutlu düzeni, çift contalı tasarımı, QMK/VIA desteği ve düğme選eneği ile tüm pratik ihtiyaçlarınızı karşılar ve size yüksek düzeyde bir yazma deneyimini sunan premium bir tam boy ve tüm metal mekanik klavyedir.",
        "zh-cn": "Keychron Q6是一款高端全尺寸和全金属机械键盘。凭借其全金属数控机械加工的机身、全尺寸布局、双胶囊设计、QMK/VIA支持和旋钮选项，Q6满足您的所有实际需求，并为您提供高端的打字体验。",
        "zh-hk": "Keychron Q6 是一款高端全尺寸及全金屬機械鍵盤，擁有全金屬CNC加工底殼、全尺寸布局、雙瓦設計、QMK/VIA支援及旋鈕選項，Q6 能滿足您的實用需求，並讓您體驗高端打字體驗。",
        "zh-tw": "Keychron Q6是一款高級全尺寸及全金屬機械鍵盤。採用全金屬CNC車削機身、全尺寸布局、雙 購物/design、QMK/VIA支援以及旋鈕選項，Q6滿足您的實際需求，並提供高檔的打字體驗。"
    },
    "collection": "Keychron Q6",
    "gallery":{},
    "attributes": [
        {
            "type": "select",
            "value": {
                "en": "Barebone",
                "es": "Esqueleto",
                "de": "Barebone",
                "fa": "اسکلتی",
                "fr": "squelette",
                "gu": "બેરબોન",
                "hi": "नंगा",
                "ja": "ベアボーン",
                "ko": "베어본",
                "pl": "bez obudowy",
                "pt-br": "Básico",
                "ro": "Schelet",
                "ru": "Зачистка",
                "tr": "İskelet",
                "zh-cn": "简化版",
                "zh-hk": "基本的",
                "zh-tw": "基本骨架"
            },
            "title": {
                "en": "Type",
                "es": "Escribir",
                "de": "Typ",
                "fa": "تیپ",
                "fr": "Taper",
                "gu": "પ્રકાર",
                "hi": "प्रकार",
                "ja": "タイプ",
                "ko": "타입",
                "pl": "Typ",
                "pt-br": "Digite",
                "ro": "Tip",
                "ru": "Тип",
                "tr": "Tür",
                "zh-cn": "类型",
                "zh-hk": "類型",
                "zh-tw": "類型"
            }
        },
        {
            "type": "buttons",
            "value": {
                "en": "Carbon Black - B",
                "es": "Carbon Black - B",
                "de": "Carbon Black - B",
                "fa": "Carbon Black - B",
                "fr": "Carbon Black - B",
                "gu": "Carbon Black - B",
                "hi": "Carbon Black - B",
                "ja": "Carbon Black - B",
                "ko": "Carbon Black - B",
                "pl": "Carbon Black - B",
                "pt-br": "Carbon Black - B",
                "ro": "Carbon Black - B",
                "ru": "Carbon Black - B",
                "tr": "Carbon Black - B",
                "zh-cn": "Carbon Black - B",
                "zh-hk": "Carbon Black - B",
                "zh-tw": "Carbon Black - B"
            },
            "title": {
                "en": "Color",
                "es": "Color",
                "de": "Farbe",
                "fa": "رنگ",
                "fr": "Couleur",
                "gu": "રંગ",
                "hi": "रंग",
                "ja": "色",
                "ko": "색",
                "pl": "Kolor",
                "pt-br": "Cor",
                "ro": "Culoare",
                "ru": "Цвет",
                "tr": "Renk",
                "zh-cn": "颜色",
                "zh-hk": "色彩",
                "zh-tw": "顏色"
            }
        },
        {
            "type": "buttons",
            "value": {
                "en": "Gateron G Pro Red",
                "es": "Gateron G Pro Rojo",
                "de": "Gateron G Pro Rot",
                "fa": "گترن جی پرو قرمز",
                "fr": "Gateron G Pro Rouge",
                "gu": "ગેટેરોન જી પ્રો રેડ",
                "hi": "गेटरन जी प्रो रेड",
                "ja": "ゲーテロンG Pro Red",
                "ko": "게이터론 G 프로 레드",
                "pl": "Gateron G Pro Czerwony",
                "pt-br": "Gateron G Pro Vermelho",
                "ro": "Gateron G Pro Roșu",
                "ru": "Gateron G Pro Red",
                "tr": "Gateron G Pro Kırmızı",
                "zh-cn": "盖特朗 G Pro 红轴",
                "zh-hk": "佳達隆 G Pro Red",
                "zh-tw": "Gateron G Pro 紅軸"
            },
            "title": {
                "en": "Switches",
                "es": "Interruptores",
                "de": "Schalter",
                "fa": "سوئیچ‌ها",
                "fr": "Interrupteurs",
                "gu": "સ્વિચ",
                "hi": "स्विच",
                "ja": "スイッチ",
                "ko": "스위치",
                "pl": "Przełączniki",
                "pt-br": "Interruptores",
                "ro": "Întrerupătoare",
                "ru": "Переключатели",
                "tr": "Anahtarlar",
                "zh-cn": "交换器",
                "zh-hk": "開關",
                "zh-tw": "開關"
            }
        }
    ]
};